server:
  port: 8081
  servlet:
    context-path: /
logging:
  file:
    path: /login/cs-auth.log
  level:
    ROOT: info
spring:
  application:
    name: cs-auth
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    timeout: 60000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mine?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    dbcp2:
      initial-size: 10
      min-idle: 10
      max-idle: 30
      max-wait-millis: 60000
      validation-query: SELECT 1 FROM DUAL
eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

