server:
  port: 8081
  servlet:
    context-path: /
logging:
  file:
    path: /login/cs-auth.log
  level:
    ROOT: info
spring:
  application:
    name: cs-auth
  redis:
    host: @redis.host@
    port: @redis.port@
    database: @redis.database@
    password: @redis.password@
    timeout: @redis.timeout@
  datasource:
    driver-class-name: @dataSource.driverClass@
    url: @dataSource.url@
    username: @dataSource.username@
    password: @dataSource.password@
    dbcp2:
      initial-size: @dbcp2.initialSize@
      min-idle: @dbcp2.minIdle@
      max-idle: @dbcp2.maxIdle@
      max-wait-millis: @dbcp2.maxWaitMillis@
      validation-query: SELECT 1 FROM DUAL
eureka:
  instance:
    ip-address: @eureka.ipaddr@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: @eureka.defaultZone@
    register-with-eureka: true
    fetch-registry: true

