server:
  port: 8082
  servlet:
    context-path: /
logging:
  file:
    path: /login/cs-gateway.log
  level:
    ROOT: info
spring:
  application:
    name: cs-gateway
  redis:
    host: @redis.host@
    port: @redis.port@
    database: @redis.database@
    password: @redis.password@
    timeout: @redis.timeout@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  instance:
    ip-address: @eureka.ipaddr@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: @eureka.defaultZone@
    fetch-registry: true
    register-with-eureka: true