server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: cs-server
eureka:
  instance:
    ip-address: @eureka.ipaddr@
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: @eureka.defaultZone@
logging:
  file:
    path: /login/cs-server.log
  level:
    ROOT: info