server:
  port: 8083
  servlet:
    context-path: /
eureka:
  instance:
    ip-address: @eureka.ipaddr@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: @eureka.defaultZone@
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: cs-utils
  redis:
    host: @redis.host@
    port: @redis.port@
    database: @redis.database@
    password: @redis.password@
    timeout: @redis.timeout@
logging:
  file:
    path: /login/cs-utils.log
  level:
    ROOT: info